# Purpose: Creates the container for running the uWaveServer software.
# Usage: podman build -t uwaveserver:latest -f Dockerfile.u24
#        buildah bud -t uwaveserver:latest -f Dockerfile.u24
FROM ubuntu:24.04
COPY @PROJECT_NAME@-@PROJECT_VERSION@-Linux.tar.gz .
LABEL version="@PROJECT_VERSION@"
RUN apt-get update &&\
    apt-get upgrade -y &&\
    apt-get autoremove -y &&\
    apt-get autoclean -y &&\
    apt-get -y install libtbb-dev &&\
    apt-get -y install bash &&\
    apt-get autoremove -y &&\
    apt-get clean &&\
    tar -xf ./@PROJECT_NAME@-@PROJECT_VERSION@-Linux.tar.gz &&\
    mv ./@PROJECT_NAME@-@PROJECT_VERSION@-Linux/bin/uDataPacketToDatabase /usr/local/bin/ &&\
    mv ./@PROJECT_NAME@-@PROJECT_VERSION@-Linux/bin/uHTTPWaveServer /usr/local/bin/ &&\
    mv ./@PROJECT_NAME@-@PROJECT_VERSION@-Linux/bin/uGRPCWaveServer /usr/local/bin/ &&\
    rm -r ./@PROJECT_NAME@-@PROJECT_VERSION@-Linux/ &&\
    rm -r /var/lib/apt/lists/* ./@PROJECT_NAME@-@PROJECT_VERSION@-Linux.tar.gz

RUN useradd -ms /bin/bash uWaveServer
WORKDIR /home/uWaveServer
