# Purpose: Creates the container for running the uWaveServer software.
# Usage: podman build -t uwaveserver:latest -f Dockerfile.deb
#        buildah bud -t uwaveserver:latest -f Dockerfile.deb
FROM ubuntu:24.04
ADD uWaveServer-@PROJECT_VERSION@-Linux.deb .
RUN apt-get update &&\ 
    apt-get upgrade -y &&\ 
    apt-get autoremove -y &&\ 
    apt-get autoclean -y &&\ 
    apt-get -y install bash &&\ 
    apt-get -y --no-install-recommends install ./uWaveServer-@PROJECT_VERSION@-Linux.deb &&\ 
    apt-get autoremove -y &&\ 
    apt-get clean &&\ 
    rm -r /var/lib/apt/lists/* uWaveServer-@PROJECT_VERSION@-Linux.deb

RUN useradd -ms /bin/bash uWaveServer
WORKDIR /home/uWaveServer
