name: uWaveServer Application
run-name: Pipeline for branch ${{ github.ref_name }}

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  BUILD_TYPE: Release
  CXX: /usr/bin/clang++
  CC: /usr/bin/clang

jobs:
  build:
    runs-on: ubuntu-24.04
    name: Build on ${{ matrix.distro }} ${{ matrix.arch }}
    #strategy:
    #  fail-fast: false
    #  matrix:
    #    BUILD_TARGET: [Release]

    steps:
      - uses: actions/checkout@v6
      # Trick next step - python checkout wants a requirements.txt file
      - run: touch requirements.txt
      - uses: actions/setup-python@v6
        with:
          python-version: '3.13'
          cache: 'pip'
      - run: pip install conan

      - name: Conan cache setup
        uses: actions/cache@v5
        id: cache-conan      
        env:
          cache-name: cache-conan-modules
        with:
          path: ~/.conan2
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('./conanfile.py') }}

      # Cache hit
      - if: ${{ steps.cache-conan.outputs.cache-hit == 'true' }}
        name: Cache hit - list the existing Conan modules
        continue-on-error: true
        run: |
          ls ~/.conan2/
          ls ~/.conan2/p
      
      - name: Create default profile with Ninja generator
        run: | 
          conan profile detect -f
          echo "" >> ~/.conan2/profiles/default
          echo "[conf]" >> ~/.conan2/profiles/default
          echo "tools.cmake.cmaketoolchain:generator=Ninja" >> ~/.conan2/profiles/default
          tail -n 50 ${HOME}/.conan2/profiles/default

      - name: Prepare environment
        uses: ./.github/actions/prepare-environment

      - name: Libmseed/Libslink cache setup
        uses: actions/cache@v5
        id: cache-libmseed-libslink      
        env:
          cache-name: cache-libmseed-libslink-modules
        with:
          path: |
             /usr/local/include/libmseed.h
             /usr/local/include/libslink.h
             /usr/local/lib/libmseed.a
             /usr/local/lib/libslink.a
          key: ${{ runner.os }}-build-${{ env.cache-name }}
      - if: ${{ steps.cache-libmseed-libslink.outputs.cache-hit != 'true' }}
        name: Build libmseed and libslink
        run: |
          wget https://github.com/EarthScope/libmseed/archive/refs/tags/v3.3.0.tar.gz
          tar -xf v3.3.0.tar.gz
          rm v3.3.0.tar.gz
          cd libmseed-3.3.0
          cmake -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=clang -DBUILD_STATIC_LIBS=ON -DBUILD_SHARED_LIBS=OFF
          cmake --build build
          sudo cmake --install build
          cd ../
          rm -rf libmseed-3.3.0 
          wget https://github.com/EarthScope/libslink/archive/refs/tags/v4.2.0.tar.gz
          tar -xf v4.2.0.tar.gz
          rm v4.2.0.tar.gz
          cd libslink-4.2.0
          CC=clang make
          sudo mv libslink.a /usr/local/lib
          sudo cp libslink.h /usr/local/include
          cd ../
          rm -rf libslink-4.2.0 
      
      - name: Install Conan dependencies
        working-directory: ${{github.workspace}}
        run: "conan install . --build=missing -s:a build_type=${{env.BUILD_TYPE}} -s:a compiler=clang -s:a compiler.version=20 -s:a compiler.cppstd=20 -s:a compiler.libcxx=libstdc++11 --output-folder ."

      - name: Configure preset and build
        working-directory: ${{github.workspace}}
        run: |
           cmake --preset conan-release -DWITH_CONAN=ON -DENABLE_COMPRESSION=ON -DENABLE_SSL=ON -DBUILD_CONTAINER=ON
           cmake --build --preset conan-release
           cp include/uWaveServer/version.hpp build
           cp CMakeUserPresets.json build

      - name: Upload build directory
        uses: ./.github/actions/upload-build-directory
        
  test:
    runs-on: ubuntu-24.04
    needs: build

    steps:
      - uses: actions/checkout@v6

      - name: Prepare test environment
        uses: ./.github/actions/prepare-environment

      - name: Download build directory
        uses: ./.github/actions/download-build-directory

      - name: Run unit tests for release
        working-directory: ${{github.workspace}}
        run: |
          mv build/version.hpp include/uWaveServer/
          mv build/CMakeUserPresets.json ./ 
          ctest --preset conan-release

  package:
    runs-on: ubuntu-24.04
    needs: test

    steps:
      - uses: actions/checkout@v6

      - name: Prepare environment
        uses: ./.github/actions/prepare-environment

      - name: Download build directory
        uses: ./.github/actions/download-build-directory

      - name: Package tgz
        working-directory: ${{github.workspace}}
        run: |
          mv build/version.hpp include/uWaveServer/
          mv build/CMakeUserPresets.json ./ 
          cd build/Release
          mkdir -p artifacts
          cpack -B artifacts TGZ

      - name: Build image
        working-directory: ${{github.workspace}}
        run: |
          cd build/Release/artifacts
          version=$(ls *tar.gz | sed 's/uWaveServer-//g' | sed 's/-Linux.tar.gz//g') 
          cd ../../../
          echo "Building container for version ${version}"
          cmake --build --preset conan-release --target buildah
          buildah tag uwaveserver:${version} quay.io/uuss/uwaveserver:${version}
          #buildah push quay.io/uuss/uwaveserver:${version}

      #- uses: actions/upload-artifact@v7
      #  with:
      #    name: uWaveServer Package
      #    path: |
      #      artifacts/uWaveServer*
      #      artifacts/Customer*.rpm        
