name: uWaveServer Application
run-name: Pipeline for branch ${{ github.ref_name }}

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-24.04
    name: Build on ${{ matrix.distro }} ${{ matrix.arch }}
    #strategy:
    #  fail-fast: false
    #  matrix:
    #    BUILD_TARGET: [Release]

    steps:
      - uses: actions/checkout@v6
      - run: |
          pwd
          ls
          touch requirements.txt

      - uses: actions/setup-python@v6
        with:
          python-version: '3.12'
          cache: 'pip'
      - run: pip install conan

      - run: |
          pwd
          ls

      - uses: actions/cache@v5
        with:
          path: |
            ${HOME}/.conan2
          key: ${{ runner.os }}-${{ hashFiles('./uWaveServer/conanfile.py') }}

      - name: Create default profile
        run: conan profile detect -f

      - name: Prepare environment
        uses: ./.github/actions/prepare-environment

      - name: Install dependencies
        working-directory: ${{github.workspace}}/build
        run: "conan install ${{github.workspace}} --build=missing -s:a build_type=${{env.BUILD_TYPE}} -pr:a=Linux-x86_64-clang -s:a --output-folder ./ -s:a compiler=clang -s:a compiler.version=20 -s:a compiler.cppstd=20 compiler.libcxx=libstdc++11"

      - name: Configure
        run: "cmake -GNinja -B ${{github.workspace}}/build -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} ${{github.workspace}}"
        
