name: uWaveServer Application
run-name: Pipeline for branch ${{ github.ref_name }}

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  BUILD_TYPE: Release
  CXX: /usr/bin/clang++
  CC: /usr/bin/clang

jobs:
  build:
    runs-on: ubuntu-24.04
    name: Build on ${{ matrix.distro }} ${{ matrix.arch }}
    #strategy:
    #  fail-fast: false
    #  matrix:
    #    BUILD_TARGET: [Release]

    steps:
      - uses: actions/checkout@v6
      # Trick next step - python checkout wants a requirements.txt file
      - run: touch requirements.txt
      - uses: actions/setup-python@v6
        with:
          python-version: '3.13'
          cache: 'pip'
      - run: pip install conan

      - uses: actions/cache@v5
        with:
          path: |
            ${HOME}/.conan2
          key: ${{ runner.os }}-${{ hashFiles('./uWaveServer/conanfile.py') }}

      - name: Create default profile with Ninja generator
        run: | 
          conan profile detect -f
          echo "" >> ${HOME}/.conan2/profiles/default
          echo "[conf]" >> ${HOME}/.conan2/profiles/default
          echo "tools.cmake.cmaketoolchain:generator=Ninja" >> ${HOME}/.conan2/profiles/default
          tail -n 50 ${HOME}/.conan2/profiles/default

      - name: Prepare environment
        uses: ./.github/actions/prepare-environment

      - name: Install dependencies
        working-directory: ${{github.workspace}}
        run: "conan install . --build=missing -s:a build_type=${{env.BUILD_TYPE}} -s:a compiler=clang -s:a compiler.version=20 -s:a compiler.cppstd=20 -s:a compiler.libcxx=libstdc++11 --output-folder ./build"

      - name: Configure preset and build
        working-directory: ${{github.workspace}}
        run: |
           cmake --preset conan-release -DWITH_CONAN=ON -DENABLE_COMPRESSION=ON -DENABLE_SSL=ON -DBUILD_CONTAINER=ON
           cmake --build --preset conan-release
           

        
